<?php
/**
 * @file Installs HumanitarianResponse Events
 */

/**
 * Implements hook_install()
 */
function humanitarianresponse_events_install() {
  
  // ShareThis configuration
  humanitarianresponse_core_sharethis_configuration('buttons', 'stbc_');
  humanitarianresponse_core_sharethis_configuration('nodeType', 'event', FALSE);
  humanitarianresponse_core_sharethis_configuration('services', '"Google:google","Tweet:twitter","Facebook:facebook","ShareThis:sharethis"');
}

